import logging

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    # Preserve semantic origin for requests already generated by the recurring-payments engine.
    cr.execute(
        """
        UPDATE soles_payment_request
           SET origin_type = 'recurring'
         WHERE recurrence_id IS NOT NULL
           AND origin_type IS DISTINCT FROM 'recurring'
        """
    )
    _logger.info("Updated %s recurring payment request origins", cr.rowcount)

    # Backfill the new reviewer on existing requests from the assigned Treasury team.
    cr.execute(
        """
        UPDATE soles_payment_request spr
           SET reviewer_id = COALESCE(stt.reviewer_id, stt.manager_id)
          FROM soles_treasury_team stt
         WHERE spr.team_id = stt.id
           AND spr.reviewer_id IS NULL
           AND COALESCE(stt.reviewer_id, stt.manager_id) IS NOT NULL
        """
    )
    _logger.info("Backfilled reviewer on %s existing payment requests", cr.rowcount)
