from . import ai_config
from . import ai_assistant
from . import ai_data_source
from . import ai_data_item
from . import ai_thread
from . import ai_message
from . import ai_message_record
from . import ai_context
from . import ai_prompt_template
from . import res_partner
from . import res_users
